In [1]:
import os
path = "C:/pytest/"
os.chdir(path)

In [2]:
def read_data(filename, encoding = 'cp949',start = 1):
    with open(filename, 'r', encoding = encoding) as f:
        data = [line.split('\t') for line in f.read().splitlines()]
        data = data[start:]
    return data
def write_data(data, filename, encoding = 'cp949'):
    with open(filename, 'w', encoding = encoding) as f:
        f.write(data)

In [3]:
data = read_data('ratings.txt', encoding='cp949')

In [4]:
from tqdm import tqdm
import rhinoMorph
rn = rhinoMorph.startRhino()

filepath:  C:\Anaconda3\lib\site-packages
classpath:  C:\Anaconda3\lib\site-packages\rhinoMorph/lib/rhino.jar
RHINO started!


In [5]:
# morphed_data = ''
# for data_each in tqdm(data):
#     morphed_data_each = rhinoMorph.onlyMorph_list(rn, data_each[1],
#                                                  pos = ['NNG','NNP','VV','VA','XR','IC','MM','MAG','MAJ'])
#     joined_data_each = ' '.join(morphed_data_each)
#     if joined_data_each:
#         morphed_data += data_each[0]+'\t'+joined_data_each+ '\t'+data_each[2]+'\n'
# write_data(morphed_data, 'ratings_morphed.txt',encoding='cp949')

In [6]:
data = read_data('ratings_morphed.txt', encoding ='cp949')
print(len(data), len(data[0]), data[0], sep = '\n')

197559
3
['8132799', '디자인 배우 학생 외국 디자이너 일구 전통 통하 발전 문화 산업 부럽 사실 우리나라 그 어렵 시절 끝 열정 지키 노라노 같 전통 있 같 사람 꿈 꾸 이루 나가 있 감사', '1']


In [7]:
import random
import math
import numpy as np

# 데이터 축소

In [8]:
random.shuffle(data)
part_num = math.floor(len(data)*1/3)
data = data[:part_num]
print(len(data))

65853


# 데이터 분리

In [9]:
data_text = [line[1] for line in data]
data_senti = [line[2] for line in data]

In [109]:
data_senti

['0',
 '1',
 '1',
 '0',
 '1',
 '0',
 '0',
 '0',
 '1',
 '0',
 '0',
 '1',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '1',
 '0',
 '1',
 '1',
 '0',
 '1',
 '0',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '0',
 '1',
 '1',
 '0',
 '1',
 '1',
 '0',
 '0',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '0',
 '0',
 '1',
 '1',
 '0',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '0',
 '0',
 '1',
 '0',
 '1',
 '0',
 '0',
 '1',
 '0',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '0',
 '1',
 '1',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '1',
 '1',
 '0'

In [10]:
from sklearn.model_selection import train_test_split
train_text, test_text, train_senti, test_senti = train_test_split(data_text, data_senti, stratify = data_senti)

In [11]:
from collections import Counter
train_senti_freq = Counter(train_senti)
print(train_senti_freq)
test_senti_freq = Counter(test_senti)
print(test_senti_freq)

Counter({'0': 24766, '1': 24623})
Counter({'0': 8256, '1': 8208})


In [12]:
text_len = [len(line.split(' ')) for line in train_text]

In [13]:
np.median(text_len)

7.0

In [14]:
print('최소길이 : {}\n최대길이 : {}\n평균길이 : {}\n중위수길이 : {}\n구간별 최대 길이 : {}\n최소길이 문장 : {}\n최대길이 문장 : {}'.format(np.min(text_len),np.max(text_len),np.round(np.mean(text_len),1), np.median(text_len), np.percentile(text_len, [0,25,50,75,90,100]), train_text[np.argmin(text_len)], train_text[np.argmax(text_len)]))

최소길이 : 1
최대길이 : 70
평균길이 : 8.8
중위수길이 : 7.0
구간별 최대 길이 : [ 1.  4.  7. 11. 19. 70.]
최소길이 문장 : 캬
최대길이 문장 : ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋ


# Tokenizing

In [15]:
# 토큰화
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import math

In [16]:
max_words = 10000 # 데이터셋에서 가장 빈도 높은 10,000 개의 단어만 사용
                  # n-1개의 단어를 가져오는 데 이는 padding을 위한 단어 하나를 남겨 둠
maxlen = 20 # 20개 이후의 단어는 버려서 각 문장의 길이를 고정
            # 20보다 길면 뒤를 자르고, 작으면 0으로 채움

In [17]:
tokenizer = Tokenizer(num_words=max_words) # 상위빈도 10,000개 단어를 추려내는 Tokenizer 객체 생성
tokenizer.fit_on_texts(train_text) # 전체 단어를 대상으로 인덱스 구축(빈도 기준)
word_index = tokenizer.word_index # 단어 인덱스 가져오기

In [18]:
print('전체 {}개\n타입 : {}\nword_index : {}'.format(len(word_index), type(word_index), word_index))

전체 21998개
타입 : <class 'dict'>
word_index : {'영화': 1, '하': 2, '보': 3, '없': 4, 'ㅋㅋ': 5, '재미있': 6, '좋': 7, '너무': 8, '되': 9, '정말': 10, '있': 11, '진짜': 12, '같': 13, '만들': 14, '말': 15, '연기': 16, '나오': 17, '최고': 18, '평점': 19, '다': 20, 'ㅋ': 21, '안': 22, '이': 23, '알': 24, '왜': 25, '스토리': 26, '이런': 27, '잘': 28, '주': 29, '드라마': 30, '때': 31, '사람': 32, '더': 33, '배우': 34, '내용': 35, '생각': 36, '가': 37, '지루': 38, '그냥': 39, '아깝': 40, '감독': 41, 'ㅠㅠ': 42, '좀': 43, '재미': 44, '재미없': 45, '시간': 46, '감동': 47, '쓰레기': 48, '다시': 49, '모르': 50, '처음': 51, '작품': 52, '마지막': 53, '아': 54, '들': 55, '액션': 56, '사랑': 57, '그': 58, '많': 59, '기대': 60, '참': 61, '못하': 62, '완전': 63, '정도': 64, '최악': 65, 'ㅎㅎ': 66, '이야기': 67, '별로': 68, '느끼': 69, '이렇게': 70, '끝': 71, '느낌': 72, '무슨': 73, '못': 74, '오': 75, '쓰': 76, '10점': 77, '남': 78, '장면': 79, '돈': 80, '지금': 81, '보이': 82, '마음': 83, '역시': 84, '명작': 85, 'ㅡㅡ': 86, '좋아하': 87, '그리고': 88, '이것': 89, '웃기': 90, '안되': 91, '주인공': 92, '한': 93, 'ㅠ': 94, '또': 95, '여자': 96, '이해': 97, '한국': 98, '살': 99

### Data Sequencing

In [19]:
# 텍스틀 숫자로 변환
data = tokenizer.texts_to_sequences(train_text)
print('data 0 : {}\n text 0 : {}'.format(data[0],train_text[0]))

data 0 : [234, 138, 100, 2735, 41, 1]
 text 0 : 개인적 가장 괜찮 임권택 감독 영화


# Data Padding

In [20]:
data = pad_sequences(data, maxlen= maxlen)
print('data : {}\ndata 0 : {}\ndata 0의 길이 : {}'.format(data,data[0],len(data[0])))

data : [[   0    0    0 ... 2735   41    1]
 [   0    0    0 ...  290   33  440]
 [ 268 4907 2736 ... 4173 9925 1498]
 ...
 [   0    0    0 ...    6    5    5]
 [   0    0    0 ...  173   84  482]
 [   0    0    0 ...  159   14    1]]
data 0 : [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
  234  138  100 2735   41    1]
data 0의 길이 : 20


# One-Hot Encoding

In [21]:
sample = [[5,6,7],[8,9,10]]
# 10은 11번째에 들어감 따라서 11개의 공간을 가진 np.array를 만듦
arr = np.zeros((len(sample), 10+1))
for i, seq in enumerate(sample):
    # 리스트가 2개 i는 총 2회
    # 각 i에서 리스트의 number가 가리키는 곳을 1을 넣음
    arr[i, seq] = 1
arr

array([[0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.]])

In [22]:
def to_one_hot(sequences, dimension):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1
    return results

In [23]:
data = to_one_hot(data, dimension=max_words)
labels = np.array(train_senti).astype('float32')

In [24]:
print(data, labels, sep = '\n\n')

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]]

[1. 0. 1. ... 1. 1. 0.]


In [25]:
print(len(data[0]),len(data),len(labels))

10000 49389 49389


In [26]:
print(type(train_text), type(data), data.shape)

<class 'list'> <class 'numpy.ndarray'> (49389, 10000)


In [27]:
print(data.ndim, labels.ndim, data.shape, labels.shape)

2 1 (49389, 10000) (49389,)


In [28]:
validation_ratio = 0.3
validation_len = math.floor(len(train_text)*validation_ratio)

# 훈련 데이터(70%)와 검증데이터(30%)를 나눔
train_X = data[validation_len:] 
train_y = labels[validation_len:]
val_X = data[:validation_len]
val_y = labels[:validation_len]

# 모델 설계

In [29]:
from keras.models import Sequential
from keras.layers import Dense

In [30]:
# model = Sequential()
# model.add(Dense(64, activation='relu', input_shape = (max_words,)))
# model.add(Dense(32, activation = 'relu'))
# model.add(Dense(1, activation = 'sigmoid'))
# model.summary()

In [31]:
# model.compile(loss= 'binary_crossentropy', optimizer = 'rmsprop', metrics = ['acc'])
# history = model.fit(train_X, train_y, epochs=10, batch_size=32, validation_data=(val_X, val_y))
# history_dict = history.history

### 모델 저장
1. save 메서드
2. pickle 라이브러리 사용

In [32]:
# model.save('./temp2/text_binary_model2.h5')

In [33]:
import pickle
# with open('./temp2/text_binary_tokenizer2.pickle','wb') as handle:
#     pickle.dump(tokenizer, handle, protocol = pickle.HIGHEST_PROTOCOL)

In [34]:
# acc = history.history['acc']
# val_acc = history.history['val_acc']
# loss = history.history['loss']
# val_loss = history.history['val_loss']

# print('Train Accuracy : {}\nValidation Accuracy : {}'.format(np.round(acc,3), np.round(val_acc,3)))

In [35]:
import matplotlib.pyplot as plt

In [36]:
# epochs = range(1,len(acc)+1)

# plt.plot(epochs, acc, 'bo',label = 'Training Acc')
# plt.plot(epochs, val_acc, 'b', label= 'Validation Acc')
# plt.plot(epochs, loss, 'ro',label = 'Training Loss')
# plt.plot(epochs, val_loss, 'r', label= 'Validation Loss')

# plt.title('Training and Validation Accuracy & Loss')
# plt.xlabel('epochs')
# plt.legend()
# plt.show()

In [37]:
from keras.models import load_model
loaded_model = load_model('./temp2/text_binary_model.h5')

with open('./temp2/text_binary_tokenizer.pickle', 'rb') as handle:
    loaded_tokenizer = pickle.load(handle)

# 테스트 데이터 처리
+ 앞선 훈련 데이터 처리한 것과 동일한 과정을 거쳐야 함

In [38]:
# 1. Tokenization
# 테스트 문자열을 word_index의 숫자 리스트로 변환
# fit_on_texts를 하지 않는 이유
# Tokenizer는 빈도를 기준으로 indexing 하기 때문에 다른 데이터를 가지고
# 토큰화하면 DTM이 달라진다.
data = loaded_tokenizer.texts_to_sequences(test_text)

In [39]:
# 2. Padding
# 문자열 길이 고정
# 타입 : 넘파이 배열
data = pad_sequences(data, maxlen = maxlen)

In [40]:
# 3. One-Hot Encoding
test_X  = to_one_hot(data, dimension= max_words)
test_y = np.asarray(test_senti).astype('float32')

In [41]:
test_eval = loaded_model.evaluate(test_X, test_y)
print(test_eval)

515/515 [==============================] - 3s 2ms/step - loss: 0.3818 - acc: 0.8348
[0.38183411955833435, 0.8347910642623901]


In [96]:
text = ['이것도 재밌네']

In [97]:
import rhinoMorph
rn = rhinoMorph.startRhino()

filepath:  C:\Anaconda3\lib\site-packages
classpath:  C:\Anaconda3\lib\site-packages\rhinoMorph/lib/rhino.jar
JVM is already started~
RHINO started!


In [98]:
text = [rhinoMorph.onlyMorph_list(rn, sentence, pos = ['NNP','NNG','VV','VA','XR','IC','MM','MAG','MAJ'], eomi = False) for sentence in text]
print(text)

[['재미있']]


In [99]:
data = loaded_tokenizer.texts_to_sequences(text)
print(data)

[[5]]


In [100]:
data = pad_sequences(data, maxlen=maxlen)
data

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5]])

In [101]:
test_X = to_one_hot(data, dimension= max_words)
test_X

array([[1., 0., 0., ..., 0., 0., 0.]])

In [102]:
test_X[0][27]

0.0

In [103]:
prediction = loaded_model.predict(test_X)
pred_ratio = round(prediction[0][0]*100,2)
print('부정 |'+'='*int(pred_ratio)+'|'+'='*(100-int(pred_ratio))+'| 긍정')
if pred_ratio > 50 :
    print('{}% 확률로 긍정입니다.'.format(pred_ratio))
elif pred_ratio < 50:
    print('{}% 확률로 부정입니다.'.format(100 - pred_ratio))
else:
    print('중립입니다.')


1/1 [==============================] - 0s 20ms/step
부정 |====================================================================================|================| 긍정
84.18% 확률로 긍정입니다.


In [105]:
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical
texts = ['우리 소망 꿈 통일']
tokenizer = Tokenizer(num_words=20)
tokenizer.fit_on_texts(texts) # DTM header 생성 -> 전체에 대한 header
word_index = tokenizer.word_index
data = tokenizer.texts_to_sequences(texts)
print(word_index)   # {'우리': 1, '소망': 2, '꿈': 3, '통일': 4}
print(data)            # [[1, 2, 3]]
print(tokenizer.texts_to_matrix(texts, mode='binary'))  # [[0. 1. 1. 1.]]
print(to_categorical(data, num_classes=20))  # [[[0. 1. 0. 0.] [0. 0. 1. 0.] [0. 0. 0. 1.]]]  #차원증가

{'우리': 1, '소망': 2, '꿈': 3, '통일': 4}
[[1, 2, 3, 4]]
[[0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [108]:
data_test = tokenizer.texts_to_matrix(train_text, mode = 'binary') 
labels = np.asarray(train_senti).astype('float32')
data_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])